import type { NextPage } from 'next';
import Head from 'next/head';
import { EmptyLayout } from '@layout/.';
import { default as LayoutPageContent } from '@pages/Landing';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Some application</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />

				<EmptyLayout>
					<LayoutPageContent />
				</EmptyLayout>
			</Head>
		</div>
	);
};

export default Home;
